name: Deploy (self-hosted)

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync repo to /opt/finterras (keep backend/.env)
        run: |
          set -euo pipefail
          sudo rsync -a --delete-after \
            --chown=gh-runner:gh-runner \
            --exclude '.git' \
            --exclude 'backend/.env' \
            "$GITHUB_WORKSPACE"/ /opt/finterras/

      - name: Clean old state
        run: |
          set -euo pipefail
          rm -rf /opt/finterras/backend/venv
          rm -rf /opt/finterras/frontend/node_modules

      - name: Restart services
        run: |
          set -euo pipefail
          sudo systemctl restart backend.service
          sudo systemctl restart frontend.service